version: "2"
services:
  backend:
    container_name: spring
    build:
      context: .
      dockerfile: backend.dockerfile
    volumes:
      - ./app:/app
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: bash -c "cd /app && ./mvnw compile package && java -jar /app/target/mx100-0.0.1-SNAPSHOT.jar"

  database:
    container_name: mysql
    image: mysql:8
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_USER: local
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: local123
      MYSQL_ROOT_PASSWORD: localroot
      MYSQL_DATABASE: mxdb
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20
    ports:
      - "3306:3306"
