CREATE TABLE `Roles` (
    `ROLE_ID` INT NOT NULL AUTO_INCREMENT,
    `ROLE_NAME` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ROLE_ID`)
);

CREATE TABLE `Users` (
    `USER_ID` INT NOT NULL AUTO_INCREMENT,
    `ROLE_ID` INT NOT NULL,
    `FULLNAME` VARCHAR(100) NOT NULL,
    `USERNAME` VARCHAR(20) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `TIMEZONE` VARCHAR(10) NOT NULL DEFAULT "UTC",
    PRIMARY KEY (`USER_ID`),
    FOREIGN KEY (`ROLE_ID`) REFERENCES `Roles` (`ROLE_ID`)
);

CREATE TABLE `Jobs` (
    `JOB_ID` INT NOT NULL AUTO_INCREMENT,
    `JOB_TITLE` VARCHAR(100) NOT NULL,
    `JOB_DESC` VARCHAR(1000) NOT NULL DEFAULT "",
    `IS_PUBLISHED` TINYINT(2) NOT NULL DEFAULT 0,
    `USER_ID` INT NOT NULL,
    `TIME_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `TIME_PUBLISHED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `TIME_CLOSED` DATETIME DEFAULT NULL,
    PRIMARY KEY (`JOB_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `Users` (`USER_ID`)
);

CREATE TABLE `Proposals` (
    `PROPOSAL_ID` INT NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR(255) NOT NULL DEFAULT "",
    `BODY` VARCHAR(1000) NOT NULL DEFAULT "",
    `TIME_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `STATUS` TINYINT(2) NOT NULL DEFAULT 0,
    `JOB_ID` INT NOT NULL,
    `USER_ID` INT NOT NULL,
    PRIMARY KEY (`PROPOSAL_ID`),
    FOREIGN KEY (`JOB_ID`) REFERENCES `Jobs` (`JOB_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `Users` (`USER_ID`)
);


INSERT INTO `Roles`
VALUES
    (1, "Employer"),
    (2, "Freelancer");

INSERT INTO `Users`
VALUES (1, 1, "Vino G Bastian", "vino", "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3", "UTC+1");
